# Generated by Django 5.0 on 2024-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articls',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Зображення'),
        ),
    ]
