# Generated by Django 5.0 on 2024-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articls_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articls',
            name='image',
            field=models.ImageField(upload_to='images/', default='default_image.jpg'),
            preserve_default=False,
        ),
    ]
