# Generated by Django 5.0 on 2024-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articls_image'),
    ]

    operations = [
    ]
