# Generated by Django 5.0 on 2024-01-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20240128_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articls',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Зображення'),
        ),
    ]
