# Generated by Django 5.0 on 2024-01-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_articls_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articls',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
